credentials:
  usernames:
    zach:
      email: zacharydietterick@yahoo.com
      name: Zach
      password: '$2b$12$EixZaYVK1fsbw1ZfbX3OXe.Rnq3G8K5ma3qZ2x4z5u6v7w8x9y0z.'   # password = "alpha"

cookie:
  name: alpha_terminal_cookie
  key: zach_alpha_terminal_super_secure_2025
  expiry_days: 30

preauthorized:
  emails:
    - zacharydietterick@yahoo.com
